BEGIN {FS=","}
{
print "    <YoungPersonsRecord>"
print "        <PersonalDetails>"
print "            <YoungPersonsID>"$1"</YoungPersonsID>"
print "            <CohortStatus>"$2"</CohortStatus>"
print "            <GivenName>"$3"</GivenName>"
print "            <MiddleName></MiddleName>"
print "            <FamilyName>"$4"</FamilyName>"
print "            <AddressLine1></AddressLine1>"
print "            <AddressLine2>"$8"</AddressLine2>"
print "            <AddressLine3>"$9"</AddressLine3>"
print "            <AddressLine4></AddressLine4>"
print "            <Town>"$11"</Town>"
print "            <County>"$12"</County>"
print "            <Postcode>"$13"</Postcode>"
print "            <Gender>"$5"</Gender>"
print "            <DOB>"$6"</DOB>"
print "            <Ethnicity>"$14"</Ethnicity>"
print "            <LeadLEA>"$15"</LeadLEA>"
print "            <EducatedLEA>"$16"</EducatedLEA>"
print "            <TransferredToLACode>"$17"</TransferredToLACode>"
print "            <LEACodeAtYear11>"$18"</LEACodeAtYear11>"
print "            <UniqueLearnerNo>"$19"</UniqueLearnerNo>"
print "            <UniquePupilNumber>"$20"</UniquePupilNumber>"
print "            <GuaranteeStatusIndicator>"$21"</GuaranteeStatusIndicator>"
print "            <PreviousYPIDIdentifier>"$22"</PreviousYPIDIdentifier>"
print "        </PersonalDetails>"
print "        <SeptemberGuarantee>"
if ($40 != "") {
print "            <Year11>"
print "                <GuaranteeStatus>"$40"</GuaranteeStatus>"
print "                <LEACode>"$41"</LEACode>"
print "            </Year11>"
}
if ($42 != "") {
print "            <Year12>"
print "                <GuaranteeStatus>"$42"</GuaranteeStatus>"
print "                <LEACode>"$43"</LEACode>"
print "            </Year12>"
}
print "        </SeptemberGuarantee>"
print "        <LevelOfNeed>"
print "            <LevelOfNeedCode>"$23"</LevelOfNeedCode>"
print "            <SENDFlag>"$24"</SENDFlag>"
print "            <SENSupportFlag>"$25"</SENSupportFlag>"
if ($39 != "") {
print "            <Characteristics>"
print "                <CharacteristicCode>"$39"</CharacteristicCode>"
print "            </Characteristics>"
}
print "        </LevelOfNeed>"
print "        <Activities>"
print "            <Cohort>"
print "                <ActivityCode>"$26"</ActivityCode>"
print "                <StartDate>"$27"</StartDate>"
print "                <DateAscertained>"$28"</DateAscertained>"
print "                <DateVerified>"$29"</DateVerified>"
print "                <ReviewDate>"$30"</ReviewDate>"
print "                <DueToLapseDate>"$31"</DueToLapseDate>"
print "                <CurrencyLapsed>"$32"</CurrencyLapsed>"
print "                <EstablishmentNumber>"$33"</EstablishmentNumber>"
print "                <EstablishmentName>"$34"</EstablishmentName>"
print "                <UKProviderReferenceNumber>"$35"</UKProviderReferenceNumber>"
print "                <NeetStartDate>"$36"</NeetStartDate>"
print "                <PredictedEndDate>"$37"</PredictedEndDate>"
print "            </Cohort>"
print "        </Activities>"
print "        <IntendedDestination>"
print "            <IntendedDestinationYr11>"$38"</IntendedDestinationYr11>"
print "        </IntendedDestination>"
print "    </YoungPersonsRecord>"
}
